### ISSUE TITLE
"SoulBringer" either crashes on main menu screen or displays a white screen depending on D3D version

### ISSUE THREAD

**Issue by ajs91** [dege-diosg/dgVoodoo2#10]
When using the D3D 12 APIs, the game will load up to the opening menu and crash within 1 second. The menu itself is displayed perfectly. Using the other hardware APIs the menu screen is a white screen with white text but there is no crash. Messed around with all the different emulated video cards and they all had the same results. Software mode works perfectly but runs slow.

**Comment by dege-diosg** [comment]
That's weird. I tested this game with v2.71.2 on both nVidia and Intel GPU's and it worked as expected.
I looked again at D3D12 debug layer output to see if an API driving error occurs here but none I found.

What type of GPU do you have? You say you get white screen with D3D11 which is a known AMD driver problem, it's suspicious it is the case here too.
What if you run the game through MS WARP (runs slowly but it's goog to check out the graphical output)?

**Comment by ajs91** [comment]
Yep, seems to be AMD related(using latest drivers). Have a laptop with an AMD 4500U/Nvidia MX350. Switched from the integrated AMD graphics to the Nvidia card and it works perfectly now. The MS WARP did work with AMD however.

**Comment by dege-diosg** [comment]
Yes, because WARP is a pure software renderer and can be used to check against hw driver errors.
