### ISSUE TITLE
DDRAW / DX7 Last Good Version 2.7 - since 2.71.1+ no Crash but Win32 Window does not resize/black screen

### ISSUE THREAD

**Issue by H-K-47** [dege-diosg/dgVoodoo2#11]
I was just trying out the latest releases, I'm using dgvodoo2 since 2016 at least and all versions seem to work fine but there has been a change since 2.71.1 /even with latest on github) that makes it no longer work with my DDRAW/DX7 MMO Game.

Is it possible to generate debug files for further analysis? 

What is happening, visually, is that the win32 window does not resize at all even though a resolution change is transmitted to dx7. I only see a black screen nothing else. The game itself is actually running fine (I can blindly perform input with the keyboard).

I could supply you with the game files and a private server account so that you can check it out yourself but maybe you already know what the issue could be.

For reference the game starts at 640x Resolution during Win32 Window Creation, and then switches to a higher resolution afterwards - this seems not to work correctly at least visually.

**Comment by dege-diosg** [comment]
Oh, it sounds bad. What game is it?
Do you get any error in the output when trying it with the dbg version of dgVoodoo?

**Comment by H-K-47** [comment]
It it is not AAOnline, it is Everquest with the Trilogy client - you can only run it with a private server which I could set you up if you give me a direct contact.

**Comment by H-K-47** [comment]
Here is the debug layer Log File - i noticed after alt tab i at least see the mouse pointer ghosting but its only the original 640x window size so i can only see a partial black screen - the window should be correctly resized
[EQC.LOG](https://github.com/dege-diosg/dgVoodoo2/files/5408667/EQC.LOG)

**Comment by dege-diosg** [comment]
That'd be cool, thanks. Unfortunately the log file doesn't contain anything interesting.
My email addr: slonderin at freemail.hu.

**Comment by H-K-47** [comment]
Great, i have sent you an email with instructions

**Comment by dege-diosg** [comment]
Issue is resolved with v2.71.3.

(The other thing we talked about is still to be investigated.)
