### ISSUE TITLE
Dungeon Keeper 2 seems to crash whenever video is played

### ISSUE THREAD

**Issue by Lrflx** [dege-diosg/dgVoodoo2#18]
Like the title says, I can bypass initial startup by removing intro files, but then you'd need to remove all curscenes to play through campaign

**Comment by dege-diosg** [comment]
That's weird. DK2 works perfectly for me, the intro video is fine.
I have to run the game in WinXP SP2 compatibility mode though.
Does that help you?

**Comment by Lrflx** [comment]
Tested it some more with different settings and still getting same results. Btw, I'm using gog version, maybe it has something to do with it, cause it has its own fixed hw renderer. And forced resolution doesn't work with it too somehow. Will try to find and test original version to be sure

**Comment by Lrflx** [comment]
Can confirm now, gog version is borked, original disk version with all the fan patches works without problems, with resolution forcing too. Guess we can close this, don't know if gog renderer could be fixed

**Comment by dege-diosg** [comment]
Ok, thanks!
I don't have the GOG version so I cannot test it, but anyway, the purpose of dgVoodoo is to be compatbile with original DX.
Unfortunately if a game is hacked in an unknown/custom way then dgVoodoo cannot guarantee compatbility. :|

So yes, let's close this issue.
