### ISSUE TITLE
Blood 2

### ISSUE THREAD

**Issue by QWERYY87** [dege-diosg/dgVoodoo2#21]
Unstable for ages. Random crashes. Sometimes right at startup. Everything tried. Another wrapper works like a charm, this won't.

**Comment by dege-diosg** [comment]
Bug resolved: another wrapper instead of dgvoodoo.

**Comment by QWERYY87** [comment]
The most technically advanced bug fixing I've ever seen.

**Comment by QWERYY87** [comment]
v2.52 works wonders with Blood 2. Something's fixed. Could be Voodoo magic. Anyway, it works for now.
