### ISSUE TITLE
Kingpin: Life of Crime

### ISSUE THREAD

**Issue by QWERYY87** [dege-diosg/dgVoodoo2#22]
Crashes when clicking "Apply" video settings in-game. Default dgVoodoo2 settings.

**Comment by dege-diosg** [comment]
It's an opengl game so I don't think it has to do anything with dgvoodoo.

**Comment by QWERYY87** [comment]
3DFX OpenGL is selectable as video output.

**Comment by dege-diosg** [comment]
Indeed, this didn't come to my mind. But anyway, dgvoodoo is not compatible with 3dfxvgl, I debugged it with other games like Soldier of Fortune, it ends up in multithreading locks in certain cases like reinitializing glide3x after changing resolution.
