### ISSUE TITLE
Many textures appear white on AMD 5700XT (ddraw.dll issue)

### ISSUE THREAD

**Issue by St0RM53** [dege-diosg/dgVoodoo2#34]
Hello. Just reporting an issue i found.

I was following this guide here in order to run the PC port of Metal Gear Solid 1 (GOG version, hotfix 4, version 41813) to run in widescreen mode:

https://www.gog.com/forum/metal_gear_series/mgs_widescreen_solution/post8

After the guide is applied if you run the game you get many white textures and especially the menu is almost completely broken on my AMD 5700XT with driver version 20.10.1

I've tried several things but the solution i found and works is to NOT replace the ddraw.dll with the dgVoodoo2 one and keep the original. Also in the "mgs1w.ini" i put the same rendering resolution as the overwrite i use in dgVoodoo2, 1440p in my case and this renders the game at that resolution fine. 

If Antialiasing is overwritten with this solution the game will launch in an infinite loop before even going to fullscreen mode and has to be killed via the task manager. 

I know dgVoodoo2 works because i can see the watermark. I use version 2.7.1.3 and even tried several older versions without the solution i wrote above but all suffer from the same issue. 

Since no-one reported such an issue i guess no-one happened to try it with the GPU i am using.

If you require further assistance for debugging like testing, screenshots, or files please let me know and i will help.

Kind regards

**Comment by dege-diosg** [comment]
It's a well known problem with AMD GPU's which has been reported (to me) a million times.
Actually #issue16 was about the same problem.
It's even mentioned in the Readme, see D3D12 section.

Use D3D12 with AMD, that should work.

**Comment by St0RM53** [comment]
Yes you are right. I've checked your solution and it works, even with MSAA enabled. I had tested the DX12 mode before but maybe i had something else wrong that prevented it from working. Thanks again, i'll close the issue.
