### ISSUE TITLE
A question about this utility

### ISSUE THREAD

**Issue by luca2125** [dege-diosg/dgVoodoo2#41]
Hi,

I ask if with this utility is possible stratch a 4:3 game to 1080p widescreen.

I Like to do it with Wing Commander Prophecy.

Actually this game use nglide (by Nexus software) but If I set fit to screen (1080p) the aspect ratio is 4:3.

Do you think this utility can solve the problem ?

Thanks !

**Comment by dege-diosg** [comment]
- Stretching a 4:3 output image to 1080p widescreen, yes, it can (distorted image)
- Extending the camera field of view to widescreen, no, it can't; you need a game specific patch for that
