### ISSUE TITLE
"Can't load KT_Game.dll" Bet on Soldier: Black-out Saigon

### ISSUE THREAD

**Issue by afarre** [dege-diosg/dgVoodoo2#42]
Hello,

I've been trying to play this 2005 game, but I constantly get the same issue. I tried various configs, virtual machines and now dgVoodoo, but still isn't working.

To see all the details, see [this StackExchange post](https://superuser.com/questions/1612607/run-2005-windows-xp-game?noredirect=1#comment2458978_1612607).

If I need to do any testing, I'll be happy to do so.

**Comment by dege-diosg** [comment]
So, this is not a dgVoodoo-specific issue.

Looking at PCGamingWiki, this game is protected by StarForce:

https://www.pcgamingwiki.com/wiki/Bet_on_Soldier:_Black-out_Saigon.

StarForce is known to be incompatible with Windows 8/10 (maybe even 7, it was an XP-era trash), and it's something to avoid as much as possible: once I installed a game (MM4 if I recall right) with StarForce, resulting in unbootable Win10.
StarForce installs itself as a kernel driver into Windows, and also overwrite the boot record on your HDD.

The only thing I can recommend is a crack for this game that removes StarForce DRM (if there is any).

**Comment by afarre** [comment]
For the last day I've tried a couple softwares for Windows XP such as CureRom, Virtual CD-Hide and SFCure, neither of them making the game work. I does not propmt the KT_Game error anymore, it only propmts for "insert CD". Maybe I didn't mention it but I tested in both in W10 and W XP.

In any case, true, it's not a dgVoodoo issue (still, if anyone knows a solution feel free to share it).

**Comment by dege-diosg** [comment]
And what if you apply a no-cd crack to the game? I just googled for it, exists.

**Comment by afarre** [comment]
I'll give it a try. So far all attempts have been either ISO that prompt for CD, or game installations which prompt for KT_Game error.
Is quite a nightmare as most links and posts are from 15 years ago. I'll keep trying, at least for the time being.

**Comment by afarre** [comment]
Managed to get it running, simply by changing iso and not using a virtual machine.
