### ISSUE TITLE
Monkey Island 4 anisotropic filtering

### ISSUE THREAD

**Issue by luca2125** [dege-diosg/dgVoodoo2#45]
Hi,

I have tested dgVoodoo with Monkey Island 4 (Escape from Monkey Island) and work fine.

The only think that add artifact (some random black lines) if I choose a Anisotropic filtering (from 2 to 16x).

Work only if I choose 1 sample.

I ask if there is a way solve the problem.

Thanks !

**Comment by dege-diosg** [comment]
I'm afraid there is no solution for that.
Forcing resolution, MSAA and texture filtering are not guaranteed features, meaning that they can easily cause artifacts in the rendering (since a particular game wasn't necessarily designed for those conditions).
