### ISSUE TITLE
[Question] What means "dbg" suffix at the release?

### ISSUE THREAD

**Issue by BlackRedDead** [dege-diosg/dgVoodoo2#46]
I couldn't find any explanation about it, neighter in the documents provided with the release nor somewhere else at the whole users repository - so what does it mean?
(As the files provided differ in size! - not only the archives but the .dll's themselves!)

**Comment by dege-diosg** [comment]
Zips with _dbg contain the builds with the debug layer and they aren't recommended for regular usage.
See more in the readme:

http://dege.fw.hu/dgVoodoo2/ReadmeGeneral/#specrelease
