### ISSUE TITLE
How to intercept D3D9.dll from the game?

### ISSUE THREAD

**Issue by legionpheonix** [dege-diosg/dgVoodoo2#48]
Let's say I have a game where D3D9.dll already exists or is used to remove the HUb interface.
Is it possible to rename the D3D9.dll file from dgvoodoo2 and intercept the file from the game?
Or am I completely delirious?

**Comment by dege-diosg** [comment]
Putting dgVoodoo D3D9 into the chain cannot be achieved by a simple renaming.
You also have to edit the D3D9.dll coming with the game, to make it search for, say, B3D9.dll and then rename dgVoodoo D3D9.dll to B3D9.dll.

So: game executable => D3D9.dll (game) => B3D9.dll (dgVoodoo)

Editing the game d3d9 is not so simple though: when it's initialized, it'll search for a D3D9.dll explicitly in the system folder, so you have to understand the disassembly of that part and replace the code in question with one searching for simply 'b3d9.dll'.

**Comment by legionpheonix** [comment]
Thank you for your answer!
Wouldn't it be difficult for you then to see the file from the game Fear 2?
[Fear2noHUD.zip](https://github.com/dege-diosg/dgVoodoo2/files/5884922/Fear2noHUD.zip)

**Comment by dege-diosg** [comment]
Ok, here you are.
Rename dgVoodoo's d3d9 to b3d9.dll.

[D3D9.zip](https://github.com/dege-diosg/dgVoodoo2/files/5899604/D3D9.zip)

(But plz ask the mod creators for other mods to patch their mods if possbile)

**Comment by legionpheonix** [comment]
THX!
