### ISSUE TITLE
Sanitarium GOG crash...

### ISSUE THREAD

**Issue by IPeluchito** [dege-diosg/dgVoodoo2#5]
Sanitarium GOG crashes randomly ... sometimes just starting the game, sometimes after a few minutes ... I have also noticed that the resolution is lost for a second sometimes and it looks pixelated, then it returns to normal ...

Windows 8.1 x64
3840x2160 Scaling at 250%
Nvidia GTX 1660Ti

**Comment by dege-diosg** [comment]
I couldn't yet reproduce it.
I tested both gog/non-gog version of the game, played around by beginning a new game but didn't experienced any problems.

Is there any extra step I should do after installing the game and before beginning playing?

**Comment by IPeluchito** [comment]
Apparently it's a game problem, it crashes also using **DXGL** ....

![Captura de pantalla (1)](https://user-images.githubusercontent.com/64821708/96779045-f1b14d80-13b1-11eb-96ce-643ffe5d006d.png)
