### ISSUE TITLE
no text displayed

### ISSUE THREAD

**Issue by ilovegithubpages** [dege-diosg/dgVoodoo2#59]
Hi
Im playing an old game "tantra online".
It has both dx8 and dx9 engine but both of them doesnt show any text when using dgVoodoo2.
I have catch a log.please help to check whats wrong.
If you need the game I can upload a minimal client.

log:https://www.dropbox.com/s/rs2tgp4ew2sz5oa/dgVoodoo2_no_text.zip?dl=0

**Comment by dege-diosg** [comment]
Thanks for the log, but I cannot see anything in that pointing to a problem.
Could you plz give me a link to the game client you're using to let me check it out myself?

**Comment by ilovegithubpages** [comment]
I have uploaded a minimal client.
Thanks.
https://www.dropbox.com/s/heq883aoeo5444v/Tantra_min_client.7z?dl=0

**Comment by dege-diosg** [comment]
Ok, thanks!
I fixed the problem, will be included in the next release.

**Comment by ilovegithubpages** [comment]
Thank you very much.
Could you provide a wip version before the next release?

**Comment by dege-diosg** [comment]
Yes, I released one yesterday, see

https://www.vogons.org/viewtopic.php?p=950667#p950667

**Comment by ilovegithubpages** [comment]
fixed in v2.74
thanks.
