### ISSUE TITLE
Tomb Raider 2 and 3 no longer work with dgVoodoo2

### ISSUE THREAD

**Issue by SAL150** [dege-diosg/dgVoodoo2#78]
Hi
Both Tomb Raider 2 and 3 wont work at all with dgVoodoo2(im on version 2.75) they just crash immediately and give no error message.
they did work before on older versions of dgVoodoo2 but im not sure which one maybe versions 2.60s?
anyway I hope you fix it soon.
i just want to add that i have tried hundreds of different settings both in the game and in dgVoodoo2, nothing works

**Comment by dege-diosg** [comment]
I've just check them out and they work with 2.75.
Maybe some settings on your game side that causes this (altough the error message 'Failed to initialize DirectX' should pop up in that case).

Recommended steps:

1) Try the games with the default config file included in the .zip
2) Try to re-setup the games (tomb2.exe -setup, tomb3.exe -setup).
3) If still crash silently then try the debug version of 2.75 and see if an error message is coming from dgVoodoo.

At the end, it may turn out that the crash is not related to dgVoodoo and reinstalling the games solves the problem.

**Comment by SAL150** [comment]
Thanks for replying
1. yes i tried that still nothing
2. yes i did this like a more than 40 time already nothing works with dgVoodoo2
3. i dont know how to use the "debug" stuff im not a programmer 
Now im sure its dgVoodoo2 because when I use the "Disable and passthru to real Directx" the game works but of course only in a small windowed mode at low resolution as all every single old game.

**Comment by dege-diosg** [comment]
You don't have to be a programmer. Just replace the dlls with the ones from the _dbg release, run DebugView++ in the background, start the game and see if any error message appears in the dbgview++ output.

**Comment by dege-diosg** [comment]
Btw, I don't know what version of the games do you have?
I use dgVoodoo with the original ones.

**Comment by SAL150** [comment]
Sorry for the late replay took me long time to find a way to fix it at least with TR2. as TR3 still not working
I use the orginal there's no any other versions to use
the solution was the dgVoodoo2 was using Config file from diffrent folder that i didnt know it exists, and had to delete it and reset the setting to default, now TR2 works perfectly . TR3 still wont launch
thanks for the help by the way :)

**Comment by dege-diosg** [comment]
I forgot to say, that I don't know if you tried the dbg version of dgVoodoo dlls after all, but they log the location where the config files are searched and read from.

**Comment by SAL150** [comment]
Thanks for all the help im closing it now.
