### ISSUE TITLE
Blitzkrieg issue - disappeared overlays

### ISSUE THREAD

**Issue by vladrrv** [dege-diosg/dgVoodoo2#85]
I've found a weird issue while using dgVoodoo2 with an old RTS game "Blitzkrieg" (it is DirectX8-based).

Blitzkrieg comes with a couple of modding tools, and one of them is an editor for creating game maps. While dgVoodoo2 is enabled, all special colored overlays on 3D objects in the map editor are not visible for some reason. Here's an example:

without dgVoodoo2 (cameras and tanks are 3D objects, bridges are 2D sprites):

![norm](https://user-images.githubusercontent.com/22059798/133828119-1bb42ea2-b59e-427c-8d99-cc295d511bec.png)

with dgVoodoo2:

![not_norm](https://user-images.githubusercontent.com/22059798/133828353-349b589f-ffa3-4bb1-a58f-e3d171136c9f.png)

As you can see, cameras and tank have lost their colored overlay, while bridge hasn't. 

I tried playing with different DirectX settings in dgVoodoo2 control panel, but with no success :(

**Comment by vladrrv** [comment]
Hmm... what version of the game have you installed? Is it patched to v1.2?
The root directory of the game should look like this:
![image](https://user-images.githubusercontent.com/22059798/136262170-cc9743ac-d9c4-46a0-9bed-196fe28c6036.png)

**Comment by dege-diosg** [comment]
Thanks!
I found the problem, the DX8 docs seems to be wrong and a particular lighting effect should work like in D3D9.
Anyway, I fixed it, it'll be included in the next version.

**Comment by dege-diosg** [comment]
I'll give a link here to the next WIP version when I release one, just to make sure if it's indeed completely fixed.

All I did was reproduced the issue by loading an available map (Italy.bzm if I remember correctly) where some tanks had blue overlay by default. I assume that fixing that particular problem implies fixing all.

**Comment by dege-diosg** [comment]
I released a WIP version, plz check it out if it solves the problem:

https://www.vogons.org/viewtopic.php?p=1008529#p1008529

(It's not infected, plz bypass antivirus.)
