### ISSUE TITLE
Clive Barker's Undying resolution problem

### ISSUE THREAD

**Issue by l0m-dev** [dege-diosg/dgVoodoo2#9]
To use 16:9 resolutions with this game I am using a custom GlideDrv.dll. If I install dgVoodoo with the custom GlideDrv.dll, the in game resolution is stuck at 512x384. With the original dll dgVoodoo works fine but not being able to use a 16:9 resolution in game is a problem.

Link to custom [GlideDrv.dll](http://www.mediafire.com/file/pg724dhhn5xhu5t/GlideDrv.zip/file)

Any help would be appreciated!

**Comment by dege-diosg** [comment]
I guess this custom dll is using the resolution hack from nglide.
dgVoodoo supports that but only if 3Dfx card type is set to 'other greater'
(VideoCard = other_greater in the [Glide] section).

I think I'll improve the debug layer to warn about this.

But honestly, why not just using DirectX instead?

**Comment by l0m-dev** [comment]
Thank you for the explanation. I'm using glide because some things just look better with the glide renderer.

**Comment by dege-diosg** [comment]
Ok...
So, does it work for you?

**Comment by l0m-dev** [comment]
Yes it does.
